//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работа_На_Объекте
    {
        public int id { get; set; }
        public Nullable<int> id_Сотрудника { get; set; }
        public Nullable<int> id_Объекта { get; set; }
        public Nullable<System.DateTime> Дата_Назначения { get; set; }
    
        public virtual Строительные_Объекты Строительные_Объекты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
