//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строительные_Объекты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Строительные_Объекты()
        {
            this.Затраты_На_Оборудование = new HashSet<Затраты_На_Оборудование>();
            this.Заявки = new HashSet<Заявки>();
            this.История_Перемещений = new HashSet<История_Перемещений>();
            this.Работа_На_Объекте = new HashSet<Работа_На_Объекте>();
            this.Распределение_Материалов_На_Объект = new HashSet<Распределение_Материалов_На_Объект>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.DateTime> Дата_Начала { get; set; }
        public Nullable<System.DateTime> Дата_Окончания { get; set; }
        public Nullable<decimal> Выделенный_Бюджет { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Затраты_На_Оборудование> Затраты_На_Оборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_Перемещений> История_Перемещений { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_На_Объекте> Работа_На_Объекте { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Распределение_Материалов_На_Объект> Распределение_Материалов_На_Объект { get; set; }
    }
}
