//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СтроительствоEntities : DbContext
    {
        public СтроительствоEntities()
            : base("name=СтроительствоEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заработная_Плата_Сотрудников> Заработная_Плата_Сотрудников { get; set; }
        public virtual DbSet<Затраты_На_Оборудование> Затраты_На_Оборудование { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<История_Перемещений_Материалов> История_Перемещений_Материалов { get; set; }
        public virtual DbSet<История_Перемещений_Оборудования> История_Перемещений_Оборудования { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Материалы_На_Складах> Материалы_На_Складах { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Оборудование_На_Складах> Оборудование_На_Складах { get; set; }
        public virtual DbSet<Отделы> Отделы { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Работа_На_Объекте> Работа_На_Объекте { get; set; }
        public virtual DbSet<Распределение_Материалов_На_Объект> Распределение_Материалов_На_Объект { get; set; }
        public virtual DbSet<Распределение_Оборудования_На_Объект> Распределение_Оборудования_На_Объект { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Строительные_Объекты> Строительные_Объекты { get; set; }
        public virtual DbSet<Уведомления> Уведомления { get; set; }
    }
}
