//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заработная_Плата_Сотрудников
    {
        public int id { get; set; }
        public Nullable<int> id_Сотрудника { get; set; }
        public Nullable<decimal> Ставка_в_День { get; set; }
        public Nullable<int> Отработано_Дней { get; set; }
        public Nullable<decimal> Затраты { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
