//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оборудование()
        {
            this.Затраты_На_Оборудование = new HashSet<Затраты_На_Оборудование>();
            this.История_Перемещений_Оборудования = new HashSet<История_Перемещений_Оборудования>();
            this.Оборудование_На_Складах = new HashSet<Оборудование_На_Складах>();
            this.Распределение_Оборудования_На_Объект = new HashSet<Распределение_Оборудования_На_Объект>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public string Тип { get; set; }
        public Nullable<int> Год_Выпуска { get; set; }
        public string Производитель { get; set; }
        public Nullable<decimal> Стоимость_в_Час { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Затраты_На_Оборудование> Затраты_На_Оборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_Перемещений_Оборудования> История_Перемещений_Оборудования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оборудование_На_Складах> Оборудование_На_Складах { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Распределение_Оборудования_На_Объект> Распределение_Оборудования_На_Объект { get; set; }
    }
}
