//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование_На_Складах
    {
        public int id { get; set; }
        public Nullable<int> id_Склада { get; set; }
        public Nullable<int> id_Оборудования { get; set; }
        public string Статус { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
        public virtual Склады Склады { get; set; }
    }
}
