//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int id { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Уровень_Доступа { get; set; }
        public Nullable<int> id_Сотрудника { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
