//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezhTransStroy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Уведомления
    {
        public int id { get; set; }
        public string Текст { get; set; }
        public Nullable<System.DateTime> Дата_Создания { get; set; }
        public Nullable<int> id_Заявки { get; set; }
    
        public virtual Заявки Заявки { get; set; }
    }
}
